### ISSUE TITLE
SNAC DB15 issue

### ISSUE THREAD

**Issue by Zagg3r** [RndMnkIII/XSleenaCore_MiSTer_Release#4]
Please fix the DB15 mapping, the buttons are all over the place. It's not usable.

**Comment by RndMnkIII** [comment]
Hi, ghe button mapping is clearly specified in the readme file. md from the project and it makes sense. Explicitly, what button mapping do you propose?

**Comment by Zagg3r** [comment]
I have a SNAC adapter (Villena's) with a DB15 Joystick and it doesn't work: Moving the joystick or pressing the buttons do nothing, I'm only able to get some reaction if I press 2 or 3 buttons together (i.e. pressing 2 or 3 buttons let me fire or jump). 
However I find it strange that while SNAC is enabled, I can still use an USB connected controller; In other cores the USB input is disabled when SNAC/DB15 is enabled.

**Comment by RndMnkIII** [comment]
Can you send my a photo of your SNAC adapter. Antonio Villena has different
models. I've tested with official MiSTer DB15 Splitter:
https://www.antoniovillena.es/store/product/splitter-for-official-mister/
In any case, I am going to rethink whether it is necessary to disable the
other inputs while DB15 is enabled.

**Comment by Zagg3r** [comment]
It's the version that plugs into the Mister DB9 connector:
![photo_2020-10-21_22-50-47-800x450](https://user-images.githubusercontent.com/119349065/210271294-5c25eb5b-dada-48ec-9d12-091d8ca73bbc.jpg)
AFAIK functionally it's the same as the official DB15. It works on every other core I tested.

**Comment by RndMnkIII** [comment]
Well, there are a number of cores with DB9, DB15 support that use a
modified version of the MiSTer Framework. I currently use the official
Framework, and for example you can't control the OSD menu with the SNAC
driver, which other cores do. There are people who are dedicated to
adapting the cores for the modified version of MiSTer, I am only interested
in offering an arcade experience of controlling the game inside the core.

**Comment by Zagg3r** [comment]
But the problems I have with the controls aren't related to the OSD/UI.
Or do you mean that there a conflict caused by the DB9 repo menu.rbf?
Do you have confirmation that the DB15 controls are working?

**Comment by RndMnkIII** [comment]
yes, tested with my official MiSTer setup. And DB15 works while USB or keyboard is connected.
